workflows:
  android-debug:
    name: Android Debug APK
    working_directory: mobile
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Generate Android project
        script: |
          flutter create . --platforms=android

      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Generate Drift code
        script: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
